version: '3.7'
services:

  ciDB:
    image: wqp_db_ci
    build:
      context: .
      dockerfile: ./database/ci/Dockerfile
    networks:
      wqp:
        ipv4_address: ${DB_CI_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${WQP_DATABASE_NAME}
      - WQP_DATABASE_NAME=${WQP_DATABASE_NAME}
      - WQP_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - WQP_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - WQP_SCHEMA_NAME=${WQP_SCHEMA_NAME}
      - WQP_SCHEMA_OWNER_USERNAME=${WQP_SCHEMA_OWNER_USERNAME}
      - WQP_SCHEMA_OWNER_PASSWORD=${WQP_SCHEMA_OWNER_PASSWORD}
      - WQP_READ_ONLY_USERNAME=${WQP_READ_ONLY_USERNAME}
      - WQP_READ_ONLY_PASSWORD=${WQP_READ_ONLY_PASSWORD}
      - CONTEXTS=external,ci,noindexes,schemaLoad
      - WQP_DATABASE_ADDRESS=127.0.0.1
    ports:
      - ${DB_CI_PORT}:5432
    container_name: ${WQP_DATABASE_ADDRESS}_ci

  demoDB:
    image: wqp_db_demo
    build:
      context: .
      dockerfile: ./database/demo/Dockerfile
    networks:
      wqp:
        ipv4_address: ${DB_DEMO_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${WQP_DATABASE_NAME}
      - WQP_DATABASE_NAME=${WQP_DATABASE_NAME}
      - WQP_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - WQP_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - WQP_SCHEMA_NAME=${WQP_SCHEMA_NAME}
      - WQP_SCHEMA_OWNER_USERNAME=${WQP_SCHEMA_OWNER_USERNAME}
      - WQP_SCHEMA_OWNER_PASSWORD=${WQP_SCHEMA_OWNER_PASSWORD}
      - WQP_READ_ONLY_USERNAME=${WQP_READ_ONLY_USERNAME}
      - WQP_READ_ONLY_PASSWORD=${WQP_READ_ONLY_PASSWORD}
      - CONTEXTS=external,dev,noindexes
      - WQP_DATABASE_ADDRESS=127.0.0.1
    ports:
      - ${DB_DEMO_PORT}:5432
    container_name: ${WQP_DATABASE_ADDRESS}_dev

  db:
    image: wqp_db
    build:
      context: .
    networks:
      wqp:
        ipv4_address: ${DB_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${WQP_DATABASE_NAME}
    ports:
      - ${DB_PORT}:5432
    container_name: ${WQP_DATABASE_ADDRESS}

  liquibase:
    image: wqp_liquibase
    build:
      context: ./liquibase
      args:
        - LIQUIBASE_VERSION=${LIQUIBASE_VERSION}
        - A_JDBC_JAR=${JDBC_JAR}
    networks:
      wqp:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WQP_DATABASE_NAME=${WQP_DATABASE_NAME}
      - WQP_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - WQP_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - WQP_SCHEMA_NAME=${WQP_SCHEMA_NAME}
      - WQP_SCHEMA_OWNER_USERNAME=${WQP_SCHEMA_OWNER_USERNAME}
      - WQP_SCHEMA_OWNER_PASSWORD=${WQP_SCHEMA_OWNER_PASSWORD}
      - WQP_READ_ONLY_USERNAME=${WQP_READ_ONLY_USERNAME}
      - WQP_READ_ONLY_PASSWORD=${WQP_READ_ONLY_PASSWORD}
      - CONTEXTS=${CONTEXTS}
      - WQP_DATABASE_ADDRESS=${WQP_DATABASE_ADDRESS}
    volumes:
      - ./liquibase/changeLogs:/home/java/workspace
      - ./liquibase/scripts/dbInit:/docker-entrypoint-initdb.d
    container_name: wqp_liquibase

networks:
  wqp:
    external:
      name: ${LOCAL_NETWORK_NAME}
