version: '3.7'
services:

  ciDB:
    image: wqp_db_ci
    build:
      context: .
      dockerfile: ./database/ci/Dockerfile
    networks:
      wqp:
        ipv4_address: ${DB_CI_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - DATA_OWNER=${DATA_OWNER}
      - DATA_OWNER_PASSWORD=${DATA_OWNER_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - SCHEMA_NAME=${SCHEMA_NAME}
      - READ_ONLY_USER=${READ_ONLY_USER}
      - READ_ONLY_USER_PASSWORD=${READ_ONLY_USER_PASSWORD}
      - CONTEXTS=external,ci,noindexes,schemaLoad
      - DATABASE_ADDRESS=127.0.0.1
    ports:
      - ${DB_CI_PORT}:5432
    container_name: ${DATABASE_ADDRESS}_ci

  demoDB:
    image: wqp_db_demo
    build:
      context: .
      dockerfile: ./database/demo/Dockerfile
    networks:
      wqp:
        ipv4_address: ${DB_DEMO_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - DATA_OWNER=${DATA_OWNER}
      - DATA_OWNER_PASSWORD=${DATA_OWNER_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - SCHEMA_NAME=${SCHEMA_NAME}
      - READ_ONLY_USER=${READ_ONLY_USER}
      - READ_ONLY_USER_PASSWORD=${READ_ONLY_USER_PASSWORD}
      - CONTEXTS=external,dev,noindexes
      - DATABASE_ADDRESS=127.0.0.1
    ports:
      - ${DB_DEMO_PORT}:5432
    container_name: ${DATABASE_ADDRESS}_dev

  db:
    image: wqp_db
    build:
      context: .
    networks:
      wqp:
        ipv4_address: ${DB_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DB_PORT}:5432
    container_name: ${DATABASE_ADDRESS}

  liquibase:
    image: wqp_liquibase
    build:
      context: ./liquibase
      args:
        - LIQUIBASE_VERSION=${LIQUIBASE_VERSION}
        - A_JDBC_JAR=${JDBC_JAR}
    networks:
      wqp:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATA_OWNER=${DATA_OWNER}
      - DATA_OWNER_PASSWORD=${DATA_OWNER_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - SCHEMA_NAME=${SCHEMA_NAME}
      - READ_ONLY_USER=${READ_ONLY_USER}
      - READ_ONLY_USER_PASSWORD=${READ_ONLY_USER_PASSWORD}
      - CONTEXTS=${CONTEXTS}
      - DATABASE_ADDRESS=${DATABASE_ADDRESS}
    volumes:
      - ./liquibase/changeLogs:/home/java/workspace
      - ./liquibase/scripts/dbInit:/docker-entrypoint-initdb.d
    container_name: wqp_liquibase

networks:
  wqp:
    external:
      name: wqp
